(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: active_sender.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Thursday, 23 July 2026 at 18:32)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.9)
(Tool: 2 -> Dia: 0.95)
(Tool: 3 -> Dia: 0.95)
(Tool: 4 -> Dia: 0.95)
(Tool: 5 -> Dia: 0.95)
(Tool: 6 -> Dia: 1.0)
(Tool: 7 -> Dia: 1.1)
(Tool: 8 -> Dia: 1.3)
(Tool: 9 -> Dia: 2.2)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 100.0)
(Tool: 3 -> Feedrate: 300)
(Tool: 4 -> Feedrate: 300)
(Tool: 5 -> Feedrate: 300)
(Tool: 6 -> Feedrate: 300)
(Tool: 7 -> Feedrate: 300)
(Tool: 8 -> Feedrate: 300)
(Tool: 9 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)
(Tool: 5 -> Feedrate Rapids: 1500)
(Tool: 6 -> Feedrate Rapids: 1500)
(Tool: 7 -> Feedrate Rapids: 1500)
(Tool: 8 -> Feedrate Rapids: 1500)
(Tool: 9 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.7)
(Tool: 2 -> Z_Cut: -1.7)
(Tool: 3 -> Z_Cut: -1.7)
(Tool: 4 -> Z_Cut: -1.7)
(Tool: 5 -> Z_Cut: -1.7)
(Tool: 6 -> Z_Cut: -1.7)
(Tool: 7 -> Z_Cut: -1.7)
(Tool: 8 -> Z_Cut: -1.7)
(Tool: 9 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 2 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)
(Tool: 5 -> Z_Move: 2)
(Tool: 6 -> Z_Move: 2)
(Tool: 7 -> Z_Move: 2)
(Tool: 8 -> Z_Move: 2)
(Tool: 9 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:    6.4100 ...   55.5750  mm)
(Y range:    7.3800 ...   66.1000  mm)

(Spindle Speed: 12000 RPM)
G21
G90
G17
G94


G01 F100.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T2
(MSG, Change to Tool Dia = 0.9500 ||| Total drills for tool T2 = 4)
M0
G00 Z15.0000
        
G01 F100.00
M03 S12000
G00 X40.0000 Y47.5000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y30.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y9.0000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X7.0000 Y47.5000
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


